# Generated by Django 3.1 on 2020-08-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_consultation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='motif',
        ),
        migrations.AddField(
            model_name='consultation',
            name='asa',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='intervention',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='intervention_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='mallampati',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
